kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.alertmanager.name }}
data:
  alertmanager.yml: |
    route:
      group_by: ['id']
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 12h
      receiver: 'web.hook'

      routes:
        - receiver: 'web.hook'
          match_re:
            severity: critical
          continue: true

    receivers:
      - name: 'web.hook'
        webhook_configs:
          - url: '{{ .Values.alertmanager.webhook_url }}'