replicaCount: 1 # If auto scale disabled

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

nameOverride: ""
fullnameOverride: ""

mongodb:
  auth:
    enabled: true
    rootUser: root
    rootPassword: "CtqcwT2RJV7XaPDALeKgfAR27gtE7fVCL6Ax3fumyLJgzS3Lh3Nffrgz2s"
    usernames: ["ms"]
    passwords: ["WNtmL3sVtHep7CSerrd2UbquuPQqmxunJJwS7Ar4oNXCBrAY5ef3BpCz2c"]
    databases: ["spawner"]

  architecture: replicaset
  arbiter:
    enabled: false

  replicaCount: 2
  externalAccess:
    enabled: true
    service:
      type: LoadBalancer
      loadBalancerIPs:
        - 10.255.37.28
        - 10.255.37.29


rabbitmq:
  auth:
    username: "user"
    password: "uzwHr6vFsBUoLfAtzQKbZnesqcBkxisH"
    securePassword: true


api:
  name: api
  service:
    type: ClusterIP
    port: 9000

  image:
    repository: "10.255.37.57:30002/ms/api"
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  podLabels: {}
  podAnnotations: {}
  imagePullSecrets: []
  env:
    - name: MONGODB_URL
      value: "mongodb://ms:WNtmL3sVtHep7CSerrd2UbquuPQqmxunJJwS7Ar4oNXCBrAY5ef3BpCz2c@10.255.37.28:27017,10.255.37.29:27017/spawner"
    - name: RABBITMQ_URL
      value: "amqp://user:uzwHr6vFsBUoLfAtzQKbZnesqcBkxisH@ms-rabbitmq/"

  livenessProbe: {}
  #  httpGet:
  #    path: /
  #    port: http
  readinessProbe: {}
  #  httpGet:
  #    path: /
  #    port: http

  volumeMounts: []
  volumes: []



