apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ name }}
  labels:
    app.kubernetes.io/name: {{ name }}
    app.kubernetes.io/instance: {{ instanceID }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ name }}
      app.kubernetes.io/instance: {{ instanceID }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ name }}
        app.kubernetes.io/instance: {{ instanceID }}
    spec:
      hostPID: true
      hostNetwork: true
      containers:
        - name: {{ .Values.snapshotter.name }}
          image: {{ .Values.snapshotter.image.repository }}:{{ .Values.snapshotter.image.tag }}
          imagePullPolicy: {{ .Values.snapshotter.image.imagePullPolicy }}
          securityContext:
            privileged: true
          volumeMounts:
          - name: containerd-sock
            mountPath: /run/containerd/containerd.sock
            readOnly: true
          ports:
            - containerPort: {{ .Values.snapshotter.port }}
              protocol: TCP
          env:
          - name: REGISTRY_URL
            value: {{ .Values.snapshotter.registry.url }}
          - name: REGISTRY_PROJECT
            value: {{ .Values.snapshotter.registry.project }}
          - name: REGISTRY_CREDS
            value: {{ .Values.snapshotter.registry.credentials }}

      volumes:
        - name: containerd-sock
          hostPath:
            path: /run/containerd/containerd.sock