harbor:
  expose:
    type: nodePort
    tls:
      enabled: false
    nodePort:
      name: harbor
      ports:
        http:
          port: 80
          nodePort: 30002
        https:
          port: 443
          nodePort: 30003
